spring.application.name=securitydemo
spring.config.import=optional:file:.env[.properties]
jwt.secret_key=${JWT_SECRET_KEY}
jwt.expiration=3600000
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
